"""Structural lint of brain outputs before they become authoritative artifacts.

Each brain.ask() can produce structurally valid (passes JSON schema) but
semantically broken output: empty strong_terms, hallucinated candidate_keys
that don't exist in the queue, over-specified phrases that match no real
papers. The fix is a cheap, deterministic, code-level linter run between
brain output and write-to-disk.

This is NOT another brain. It's a parser-style structural check, like a
compiler complaining about un-typed AST nodes before code-gen. Cross-model
audit (separate command) is the semantic-level reviewer; lint is the
structural-level reviewer.

Severity contract:
- "critical": writing this output will produce broken / unrecoverable state.
  Caller should retry the brain (with the lint feedback in the prompt) or
  abort the stage.
- "warning": output is usable but has known smells that should be logged
  to state.json so a human can spot them later.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from ..roles import BACKGROUND_ANCHOR, BOUNDARY_NEGATIVE, normalize_role, seed_required
from ..text import normalize_title


@dataclass
class LintIssue:
    severity: str  # "critical" | "warning"
    code: str
    message: str

    def is_critical(self) -> bool:
        return self.severity == "critical"

    def to_dict(self) -> dict[str, str]:
        return {"severity": self.severity, "code": self.code, "message": self.message}


def lint_plan_output(parsed: Any, direction: str = "") -> list[LintIssue]:
    """Validate a brain plan response against the v3 contract.

    v3 expects:
      - search_hints: 4-12 query strings for source recall
      - search_keyword_text: a paragraph for embedding similarity
      - judge_examples: in_scope + out_of_scope anchor lists
      - no seed_papers from the brain; source-backed anchors are generated by code
    """
    issues: list[LintIssue] = []
    if not isinstance(parsed, dict):
        issues.append(LintIssue("critical", "plan_not_dict", "plan response is not a dict"))
        return issues

    search_hints = parsed.get("search_hints") or []
    valid_hints = [h.strip() for h in search_hints if isinstance(h, str) and h.strip()]
    if len(valid_hints) < 3:
        issues.append(LintIssue(
            "critical",
            "search_hints_too_few",
            f"plan has fewer than 3 search_hints (got {len(valid_hints)}); "
            "recall stage needs at least a few query variants",
        ))
    elif len(valid_hints) < 5:
        issues.append(LintIssue(
            "warning",
            "search_hints_thin",
            f"only {len(valid_hints)} search_hints; aim for 6-10 for good recall coverage",
        ))

    keyword_text = (parsed.get("search_keyword_text") or "").strip()
    if not keyword_text:
        issues.append(LintIssue(
            "warning",
            "no_keyword_text",
            "search_keyword_text is empty; embedding channel will fall back to "
            "joining search_hints (less rich similarity target)",
        ))
    elif len(keyword_text.split()) < 20:
        issues.append(LintIssue(
            "warning",
            "keyword_text_short",
            f"search_keyword_text only {len(keyword_text.split())} words; "
            "60-150 word paragraph gives the embedding model more signal",
        ))

    examples = parsed.get("judge_examples") or {}
    if not isinstance(examples, dict):
        issues.append(LintIssue(
            "critical",
            "judge_examples_malformed",
            "judge_examples must be an object with in_scope and out_of_scope arrays",
        ))
    else:
        in_scope = [
            e for e in (examples.get("in_scope") or [])
            if isinstance(e, dict) and (e.get("title") or "").strip()
        ]
        out_scope = [
            e for e in (examples.get("out_of_scope") or [])
            if isinstance(e, dict) and (e.get("title") or "").strip()
        ]
        if len(in_scope) < 3:
            issues.append(LintIssue(
                "critical",
                "in_scope_examples_too_few",
                f"need ≥3 in_scope judge_examples (got {len(in_scope)}); "
                "the LLM judge needs anchors to score against",
            ))
        if len(out_scope) < 3:
            issues.append(LintIssue(
                "critical",
                "out_of_scope_examples_too_few",
                f"need ≥3 out_of_scope judge_examples (got {len(out_scope)}); "
                "without out anchors the judge over-accepts",
            ))

    return issues


def repair_plan_seed_contract(parsed: Any) -> list[LintIssue]:
    """Apply conservative, deterministic seed-contract repairs in place.

    This only touches seeds that are simultaneously required, non-background,
    and self-contradictory: they either duplicate an out-of-scope example or
    explain themselves as contrast/out-of-scope. Such rows are useful as
    boundary negatives, but should not become must-recall core papers.
    """
    if not isinstance(parsed, dict):
        return []
    examples = parsed.get("judge_examples") or {}
    if not isinstance(examples, dict):
        return []
    out_titles_norm = {
        normalize_title(e.get("title") or "")
        for e in (examples.get("out_of_scope") or [])
        if isinstance(e, dict) and (e.get("title") or "").strip()
    }
    out_titles_norm.discard("")
    out_phrases = (
        "not slm", "not in scope", "out of scope", "useful as contrast",
        "for contrast", "as a counter", "counter-example", "out-of-scope",
    )
    repaired: list[str] = []
    for seed in parsed.get("seed_papers") or []:
        if not isinstance(seed, dict):
            continue
        role = normalize_role(seed.get("paper_role") or seed.get("role"))
        if role in {BACKGROUND_ANCHOR, BOUNDARY_NEGATIVE} or not seed_required(seed):
            continue
        title = (seed.get("title") or "").strip()
        title_conflict = normalize_title(title) in out_titles_norm
        why = (seed.get("why_seed") or seed.get("reason") or "").lower()
        reason_conflict = any(phrase in why for phrase in out_phrases)
        if not title_conflict and not reason_conflict:
            continue
        seed["paper_role"] = BOUNDARY_NEGATIVE
        seed["required"] = False
        repaired.append(title or "<untitled>")
    if not repaired:
        return []
    return [LintIssue(
        "warning",
        "seed_auto_downgraded_to_boundary_negative",
        f"{len(repaired)} contradictory required seed_papers were downgraded "
        f"to boundary_negative required=false (e.g. {repaired[0]!r})",
    )]


def filter_hallucinated_decisions(
    decisions: list[Any],
    queue_keys: set[str],
) -> tuple[list[dict[str, Any]], list[LintIssue]]:
    """Drop decisions whose candidate_key isn't in the queue. Returns the
    cleaned list and the warnings describing what was dropped.

    queue_keys must be the exact set of candidate_keys present in the review
    queue; brain may also leave the key empty and only fill `title`, in
    which case the caller does title-based fallback later — those rows are
    passed through unchanged here.
    """
    issues: list[LintIssue] = []
    cleaned: list[dict[str, Any]] = []
    # Brain sometimes drops trailing punctuation (e.g. `;`) from compound DBLP
    # keys when echoing them back. Build a lenient lookup from semicolon-
    # stripped form → exact queue key so we can remap instead of dropping.
    lenient_lookup: dict[str, str] = {}
    for qk in queue_keys:
        stripped = qk.rstrip(";").strip()
        if stripped and stripped != qk and stripped not in queue_keys:
            lenient_lookup[stripped] = qk
    for idx, dec in enumerate(decisions or []):
        if not isinstance(dec, dict):
            continue
        key = (dec.get("candidate_key") or "").strip()
        if key and key not in queue_keys:
            remap = lenient_lookup.get(key.rstrip(";").strip())
            if remap:
                dec["candidate_key"] = remap
                cleaned.append(dec)
                continue
            issues.append(LintIssue(
                "warning",
                "dropped_hallucinated_key",
                f"decision[{idx}] candidate_key={key!r} not in queue, dropped",
            ))
            continue
        cleaned.append(dec)
    return cleaned, issues


def issues_summary(issues: list[LintIssue]) -> dict[str, Any]:
    """Compact dict suitable for state.end_stage(...lint=...) annotations."""
    by_code: dict[str, int] = {}
    for issue in issues:
        by_code[issue.code] = by_code.get(issue.code, 0) + 1
    return {
        "total": len(issues),
        "critical": sum(1 for i in issues if i.severity == "critical"),
        "warnings": sum(1 for i in issues if i.severity == "warning"),
        "by_code": by_code,
        "messages": [i.to_dict() for i in issues],
    }


def format_issues_for_prompt(issues: list[LintIssue]) -> str:
    """Render issues as a human-readable block to inline into a retry
    prompt so the brain can see what went wrong on the last attempt."""
    lines = ["The previous output was rejected by the structural linter:"]
    for issue in issues:
        lines.append(f"- [{issue.severity}] {issue.code}: {issue.message}")
    lines.append("")
    lines.append("Fix all critical issues and resubmit. Do NOT echo the lint feedback in your output.")
    return "\n".join(lines)
